return {
 {id="explorer",title="File Explorer",icon="EX",file="programs/explorer.lua",w=44,h=19},
 {id="calculator",title="Calculator",icon="CAL",file="programs/calculator.lua",w=36,h=19},
 {id="notes",title="Notepad",icon="TXT",file="programs/notes.lua",w=52,h=20},
 {id="paint",title="Paint",icon="ART",file="programs/paint.lua",w=52,h=21},
 {id="clock",title="Clock",icon="CLK",file="programs/clock.lua",w=36,h=15},
 {id="calendar",title="Calendar",icon="DATE",file="programs/calendar.lua",w=42,h=18},
 {id="settings",title="Settings",icon="SET",file="programs/settings.lua",w=48,h=19},
 {id="system",title="Task Manager",icon="SYS",file="programs/system.lua",w=48,h=19},
 {id="browser",title="Web",icon="WEB",file="programs/browser.lua",w=52,h=20},
 {id="mail",title="Mail",icon="MAIL",file="programs/mail.lua",w=52,h=20},
 {id="store",title="App Center",icon="APP",file="programs/store.lua",w=48,h=19},
 {id="terminal",title="Command Center",icon=">_",file="programs/terminal.lua",w=48,h=19},
 {id="devices",title="Devices",icon="DEV",file="programs/devices.lua",w=54,h=21},
 {id="monitor",title="Monitor Studio",icon="MON",file="programs/monitor.lua",w=44,h=19},
 {id="printer",title="Printer",icon="PRN",file="programs/printer.lua",w=44,h=19},
 {id="sound",title="Sound Center",icon="SND",file="programs/sound.lua",w=44,h=19},
 {id="network",title="Network Center",icon="NET",file="programs/network.lua",w=44,h=19},
 {id="disks",title="Disk Manager",icon="DSK",file="programs/disks.lua",w=48,h=19},
 {id="redstone",title="Redstone Control",icon="RS",file="programs/redstone.lua",w=44,h=19}
}
