term.setBackgroundColor(colors.black); term.setTextColor(colors.white); term.clear(); term.setCursorPos(2,2)
print("OScctweaked")
print("Touchscreen OS for CC:Tweaked")
print("")
print("Version: 0.1.0")
print("Developer: Frez7373")
print("")
print("Press any key to return...")
os.pullEvent("key")
